# Change these first
owner: Index-Interactive # Your GitHub organization or username, where this repository lives
repo: Status # The name of this repository

sites:
  - name: Index.ba
    url: https://index.ba
  - name: Index.ba Status
    url: https://status.index.ba
  - name: Index.ba Search Engine
    url: https://index.ba/?s=index
  - name: Index.ba Najnovije
    url: https://index.ba/najnovije/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.status.index.ba
  # baseUrl: /your-repo-name
  logoUrl: https://index.ba/favicon.ico
  name: Index.ba Status
  introTitle: "Index.ba Status page"
  introMessage: Check if Index.ba is up or down
  navbar:
    - title: Index.ba
      href: https://index.ba
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
